# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LegendsTour' do
  # Comment the next line if you don't want to use dynamic frameworks
  

  # Pods for LegendsTour
# Required by RNFirebase
pod 'Firebase/Core', '~> 6.3.0'
pod 'Firebase/Messaging', '~> 6.3.0'

  target 'LegendsTour-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LegendsTourTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'LegendsTour-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks

 

end
