require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '9.0'

target 'legendstourrr' do
  config = use_native_modules!
  pod 'Firebase/Core', '~> 6.13.0'
  use_react_native!(:path => config["reactNativePath"])

  target 'legendstourrrTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'legendstourrr-tvOS' do
  # Pods for legendstourrr-tvOS

  target 'legendstourrr-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
